name: pkuwwt
description: 技术博客
url: http://pkuwwt.github.io
permalink: /:categories/:year-:month-:day-:title/
relative_permalinks: false
markdown: kramdown
#markdown: rdiscount
#markdown: redcarpet
baidu_tongji_id: 3F3d35307f190110ab5152701a7ffb30f7
baseurl: 
